version: '3.8'

services:
  go:
    build:
      context: ./go
    ports:
      - "8080:8080"

  nextjs:
    build:
      context: ./nextjs
    ports:
      - "3000:3000"

  wordpress:
    build:
      context: ./wordpress
    ports:
      - "80:80"
