name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install GolangCI-Lint
        run: go get github.com/golangci/golangci-lint/cmd/[email protected]

      - name: Linting and Testing
        run: golangci-lint run ./... && go test ./...

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker build -t myapp-go .

  # push:
  #   name: Push Docker Image
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Push Docker Image to Docker Hub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Tag Docker Image
  #       run: |
  #         docker tag myapp-go ${{ secrets.DOCKER_USERNAME }}/myapp-go:latest

  #     - name: Push Docker Image
  #       run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp-go:latest

  # deploy:
  #   name: Deploy to Production
  #   runs-on: ubuntu-latest
  #   needs: push
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   steps:
  #     - name: Deploy to Production
  #       # Add your deployment steps here
